version: '3.7'

services:
  registry:
    image: registry:2
    restart: always
    volumes:
      - ./files/config.yml:/etc/docker/registry/config.yml:ro
      - ./files/passwd:/auth/passwd:ro
      - ./volumes/registry:/var/lib/registry
    ports:
      - 5000:5000

